# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-12 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='default name', max_length=60, null=True)),
                ('desc', models.CharField(blank=True, default='default desc', max_length=60, null=True)),
            ],
        ),
    ]
