# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-13 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='postdata',
            name='title',
        ),
        migrations.AddField(
            model_name='postdata',
            name='password',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='postdata',
            name='username',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
