# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-13 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180813_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=60, null=True)),
                ('password', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='postdata',
            name='password',
        ),
        migrations.RemoveField(
            model_name='postdata',
            name='username',
        ),
        migrations.AddField(
            model_name='postdata',
            name='desc',
            field=models.CharField(blank=True, default='default desc', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='postdata',
            name='title',
            field=models.CharField(blank=True, default='default name', max_length=60, null=True),
        ),
    ]
